# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e6f7c027668b3e7d564b8198bec74bc2ce12080e85af2683ef1838b459c5c936ea070761ce48418e9459ea00b32914496f1406fbfe5d0c1e286cabe2e6ec879e

test:
  secret_key_base: fe0603a2ad399bdda25ad17df93a7510022c5ba87fc5584331cc198a23fc0f953bc08f5fe2661d6496a2852ed64806e96e907cfe917b9b0e2c35475872b08474

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
